###
#
#  Created under not commercial project "Make it fine"
#
#  Copyright 2017-2020
#
###

## It's main timeout configuration for server and security in Spring
server:
  servlet:
    session:
      timeout: 1h
  port: ${PORT:8080}

spring:
  session:
    timeout: 1h
