###
#  Created under not commercial project "Make it fine"
#
#  Copyright 2017-2020
###

security:
  enable: false

spring:
  profiles:
    include: config_h2, config_mvc
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
