###
#  Created under not commercial project "Make it fine"
#
#  Copyright 2017-2020
###

spring:
  kafka:
    bootstrap-servers: ${spring.embedded.kafka.brokers}
    topic:
      hello: test.mif.event.hello
      bye: test.mif.event.bye
      message: test.mif.event.message
