###
#  Created under not commercial project "Make it fine"
#
#  Copyright 2017-2020
###

server:
  port: ${PORT:8085}

spring:
  kafka:
    bootstrap-servers: @kafka.hostPort@
    group-id: group_id
    auto-offset-reset: earliest
    topic:
      hello: mif.event.hello
      bye: mif.event.bye
      message: mif.event.message
